CREATE TABLE DEPARTMENT(
     DEPT_ID INT PRIMARY KEY,
     DEPT_NAME VARCHAR(100) NOT NULL,
     HOD VARCHAR(100),
     BUILDING VARCHAR(50),
     FLOOR INT,
     ROOM INT);


 CREATE TABLE DEPARTMENT_CONTACT(
     DEPT_ID INT,
     PHONE_NO VARCHAR(15),
     PRIMARY KEY(DEPT_ID,PHONE_NO),
     FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID));


CREATE TABLE DOCTOR(
     DOCTOR_ID INT PRIMARY KEY,
     F_NAME VARCHAR(50),
     M_NAME VARCHAR(50),
     L_NAME VARCHAR(50),
     SPECIALISATION VARCHAR(100),
     EXPERIENCE INT,
     DEPT_ID INT,
     FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID));


CREATE TABLE DOCTOR_CONTACT(
     DOCTOR_ID INT,
     PHONE_NO VARCHAR(15),
     PRIMARY KEY(DOCTOR_ID,PHONE_NO),
     FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID));


CREATE TABLE Patient (
     patient_id INT PRIMARY KEY,
     f_name VARCHAR(50),
     m_name VARCHAR(50),
     l_name VARCHAR(50),
     age INT,
     gender VARCHAR(10));


CREATE TABLE PATIENT_PHONE(
     PATIENT_ID INT,
     PHONE_NO VARCHAR(15),
     PRIMARY KEY(PATIENT_ID, PHONE_NO),
     FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID));


CREATE TABLE APPOINTMENT(
     APT_ID INT PRIMARY KEY,
     APT_DATE DATE,
     APT_TIME TIME,
     DOCTOR_ID INT,
     PATIENT_ID INT,
     FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID),
     FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID));


CREATE TABLE PRESCRIPTION(
     PRESC_ID INT PRIMARY KEY,
     ISSUED_DATE DATE,
     DOCTOR_ID INT,
     PATIENT_ID INT,
     APT_ID INT,
     FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID),
     FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
     FOREIGN KEY(APT_ID) REFERENCES APPOINTMENT(APT_ID));


CREATE TABLE PRESCRIPTION_MEDICINE(
     PRESC_ID INT,
     MEDICINE_NAME VARCHAR(100),
     PRIMARY KEY (PRESC_ID, MEDICINE_NAME),
     FOREIGN KEY (PRESC_ID) REFERENCES PRESCRIPTION(PRESC_ID));




